### PR TITLE
Created sprint-apply-custom-map-layers WMS ID:11088

### PR DESCRIPTION
**Pull request by malia-german**
Also included were some edits to analytics/sprint-oas-creating-custom-map-layers/manifest.json

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please include the workshop’s WMS ID in the title of the PR

**Comment by arabellayao** [comment]
Please fix the merge conflicts.

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved 
Conflicting files
analytics/sprint-oas-creating-custom-map-layers/manifest.json

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop #11088. Can you ask someone in the workshop team to add you as the workshop team?

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
