### PR TITLE
WMS ID 11257

### PR DESCRIPTION
**Pull request by isabelcgomes**
# WMS ID 11257

# General information
This PR is focused on translating sprints from english to portuguese. 
All translated sprints were reviewed and double checked on links working, images with alternate texts and manifests properly functionate

# Checklist
All checklist items were reviewed and properly checked

### CODE REVIEW

**Comment by anooshapilli** [comment]
@isabelcgomes -There are no markdown changes in the PR. Could you confirm if the changes in the PR are final?

**Comment by isabelcgomes** [comment]
@anooshapilli yes, those are the final files

**Review by anooshapilli — CHANGES_REQUESTED** [review]
With the recent changes, you are deleting a few sprints. Could you revert the changes you made?

**Comment by isabelcgomes** [comment]
Sure!

**Comment by anooshapilli** [comment]
@isabelcgomes @ThaisHenrique - Closing this PR. As discussed over the call, resolve the deleted files issue, sync your repo and create a new PR.

**Pull request closed without merging**
